### ISSUE TITLE
tolua运行项目栈溢出

### ISSUE THREAD

**Issue by Gtane** [ElPsyCongree/LuaProfiler-For-Unity#2]
我使用的2.0版的，一运行项目就栈溢出。
然后我修改了Sample.cs 第148行，把“item.fahter = this;”修改为“item.fahter = s;”，就好了

**Comment by Gtane** [comment]
用于采样的缓存容器是List，我在跑call次数多的逻辑代码非常卡，用List模拟Stack的Pop操作对于比较大的List开销很客观，所以我修改了一下LuaProfiler，把容器类型改成stack，变得流畅了很多，希望这个工具越做越好！
[LuaProfiler.txt](https://github.com/ElPsyCongree/LuaProfiler/files/2632381/LuaProfiler.txt)

**Comment by ElPsyCongree** [comment]
使用最新的2.0之前是beta版本
