### ISSUE TITLE
可以把Client和Server部分放在一起么？打开两个工程太麻烦

### ISSUE THREAD

**Issue by jerry-zeng** [ElPsyCongree/LuaProfiler-For-Unity#6]
#if UNITY_EDITOR && A_FLAG的时候就绕过开多线程和Scoket，向Client/Server直接传数据，理论上实现起来不麻烦，不知道你们踩到什么坑，要把它们放到两个工程里。

**Comment by ElPsyCongree** [comment]
有个分支 localmode

**Comment by ElPsyCongree** [comment]
主要有三个原因，1、可以兼容非 5.6的版本；2、可以真机看结果；3、treeview节点多的时候 会卡 游戏本身的渲染。 其实有个分支localmode的

**Comment by ElPsyCongree** [comment]
补充一下，Profiler 本身 会占用 一定的 内存资源。如果直接抓，容易混在一起，导致结果不准
